ALTER TABLE "Service"
  ADD COLUMN IF NOT EXISTS "pricingUnit" TEXT NOT NULL DEFAULT 'PER_PERSON';

UPDATE "Service"
SET "pricingUnit" = 'PER_PACKAGE'
WHERE "type" IN ('EXCLUSIVE_EXPERIENCE', 'CABIN_CHARTER');
