import type { IslandId, IslandMapData, IslandPoi } from "./types";

export const favignanaPois: IslandPoi[] = [
  { id: "punta-ferro", label: "Punta Ferro", x: 18, y: 20 },
  { id: "cala-del-pozzo", label: "Cala del Pozzo", x: 24, y: 25.8 },
  { id: "punta-faraglione", label: "Punta Faraglione", x: 38, y: 7 },
  { id: "cala-trapanese", label: "Cala Trapanese", x: 41, y: 12 },
  { id: "castello-s-caterina", label: "Castello di S. Caterina", x: 38, y: 48 },
  { id: "tonnara", label: "Tonnara", x: 46, y: 41 },
  { id: "porto", label: "Porto", x: 51, y: 42 },
  { id: "palazzo-florio", label: "Palazzo Florio", x: 53, y: 50 },
  { id: "cala-graziosa", label: "Cala Graziosa", x: 62, y: 36.5 },
  { id: "punta-s-nicola", label: "Punta S. Nicola", x: 67, y: 36.3 },
  { id: "cala-s-nicola", label: "Cala S. Nicola", x: 70, y: 43.8 },
  { id: "scalo-cavallo", label: "Scalo Cavallo", x: 72, y: 51.3 },
  { id: "cala-rossa", label: "Cala Rossa", x: 79, y: 59 },
  { id: "punta-s-vituzzo", label: "Punta S. Vituzzo", x: 82, y: 56 },
  { id: "cave-florio", label: "Cave Florio", x: 75, y: 62.6 },
  { id: "bue-marino", label: "Bue Marino", x: 84.5, y: 70 },
  { id: "punta-marsala", label: "Punta Marsala", x: 82, y: 87 },
  { id: "cala-azzurra", label: "Cala Azzurra", x: 77.5, y: 84 },
  { id: "punta-fanfalo", label: "Punta Fanfalo", x: 72, y: 91.5 },
  { id: "cala-tuono", label: "Cala Tuono", x: 69, y: 85 },
  { id: "grotta-perciata", label: "Grotta Perciata", x: 66, y: 76.2 },
  { id: "lido-burrone", label: "Lido Burrone", x: 59, y: 67 },
  { id: "cala-monaci", label: "Cala Monaci", x: 49, y: 70 },
  { id: "punta-longa", label: "Punta Longa", x: 47, y: 77 },
  { id: "marasolo", label: "Marasolo", x: 46, y: 66 },
  { id: "isola-preveto", label: "Isola Preveto", x: 35, y: 73 },
  { id: "galeotta", label: "Galeotta", x: 31, y: 75.8 },
  { id: "cala-s-antonio", label: "Cala S. Antonio", x: 28, y: 71 },
  { id: "punta-galera", label: "Punta Galera", x: 23, y: 74 },
  { id: "cala-rotonda", label: "Cala Rotonda", x: 20, y: 59 },
  { id: "cala-grande", label: "Cala Grande", x: 17, y: 46 },
  { id: "punta-sottile", label: "Punta Sottile", x: 12.5, y: 39.7 },
];

export const levanzoPois: IslandPoi[] = [
  { id: "capo-grosso", label: "Capo Grosso", x: 49, y: 4 },
  { id: "cala-tramontana", label: "Cala Tramontana", x: 35, y: 32.3 },
  { id: "punta-surci", label: "Punta Surci", x: 29, y: 35.3 },
  { id: "grotta-del-bue", label: "Grotta del Bue", x: 31, y: 74.3 },
  { id: "faraglione", label: "Faraglione", x: 39.5, y: 91 },
  { id: "cala-camarro", label: "Cala Camarro", x: 44, y: 92 },
  { id: "punta-pesce", label: "Punta Pesce", x: 55, y: 95.6 },
  { id: "cala-dogana", label: "Cala Dogana", x: 56, y: 90.3 },
  { id: "cala-fredda", label: "Cala Fredda", x: 63, y: 85 },
  { id: "punta-s-leonardo", label: "Punta S. Leonardo", x: 71, y: 86.3 },
  { id: "cala-minnola", label: "Cala Minnola", x: 70.7, y: 76.5 },
  { id: "punta-altarella", label: "Punta Altarella", x: 73, y: 70.3 },
  { id: "cala-calcara", label: "Cala Calcara", x: 63.3, y: 57.7 },
  { id: "pizzo-del-corvo", label: "Pizzo del Corvo", x: 53, y: 41 },
  { id: "palazzo-florio", label: "Palazzo Florio", x: 57, y: 61 },
  { id: "paese", label: "Paese", x: 54.3, y: 85.9 },
  { id: "grotta-del-genovese", label: "Grotta del Genovese", x: 30, y: 55 },
  { id: "grotta-ivana", label: "Grotta Ivana", x: 42, y: 34 },
  { id: "pizzo-del-monaco", label: "Pizzo del Monaco", x: 41, y: 58 },
];

export const marettimoPois: IslandPoi[] = [
  { id: "manione", label: "Manione", x: 52.6, y: 16.4 },
  { id: "punta-troia", label: "Punta Troia", x: 54.6, y: 7.3 },
  { id: "grotta-del-tuono", label: "Grotta del Tuono", x: 51.7, y: 5.4 },
  { id: "castello-di-punta-troia", label: "Castello di Punta Troia", x: 52.3, y: 10.4 },
  { id: "scalo-maestro", label: "Scalo Maestro", x: 49.9, y: 10.2 },
  { id: "grotta-della-pipa", label: "Grotta della Pipa", x: 47.6, y: 11 },
  { id: "praia-libano", label: "Praia Libano", x: 44.4, y: 10.4 },
  { id: "due-frati", label: "Due Frati", x: 40.2, y: 8.9 },
  { id: "capo-bianco", label: "Capo Bianco", x: 35.3, y: 16.6 },
  { id: "pizzo-fraule", label: "Pizzo Fraule", x: 40, y: 22.4 },
  { id: "portella-madonnuzza", label: "Portella Madonnuzza", x: 47.8, y: 19.7 },
  { id: "pizzo-falcone", label: "Pizzo Falcone", x: 43.3, y: 31.7 },
  { id: "pizzo-craparo", label: "Pizzo Craparo", x: 46, y: 42.7 },
  { id: "pizzo-scaturro", label: "Pizzo Scaturro", x: 45.9, y: 62.4 },
  { id: "pizzo-michelino", label: "Pizzo Michelino", x: 50.9, y: 57.9 },
  { id: "portella-anzini", label: "Portella Anzini", x: 52.9, y: 63.1 },
  { id: "pizzo-telegrafo", label: "Pizzo Telegrafo", x: 56.5, y: 66.4 },
  { id: "pizzo-lisciannaro", label: "Pizzo Lisciannaro", x: 57.8, y: 70.5 },
  { id: "pizzo-spiruni", label: "Pizzo Spiruni", x: 60.2, y: 75.5 },
  { id: "mira-di-basano", label: "Mira di Basano", x: 69.2, y: 87.3 },
  { id: "a-balata-a-lera", label: "A Balata 'a Lera", x: 32.7, y: 7.1 },
  { id: "punta-mugnone", label: "Punta Mugnone", x: 27.4, y: 7 },
  { id: "cala-bianca", label: "Cala Bianca", x: 28.7, y: 16.6 },
  { id: "grotta-perciata", label: "Grotta Perciata", x: 30.7, y: 25.1 },
  { id: "grotta-ficara", label: "Grotta Ficara", x: 31.8, y: 30.9 },
  { id: "grotta-del-presepe", label: "Grotta del Presepe", x: 34.1, y: 43.6 },
  { id: "i-ruttiddri", label: "I Rutiddri", x: 36.4, y: 49.8 },
  { id: "grotta-della-bombarda", label: "Grotta della Bombarda", x: 36.3, y: 54.5 },
  { id: "spalmatore", label: "Spalmatore", x: 37.6, y: 59.1 },
  { id: "punta-libeccio", label: "Punta Libeccio", x: 35.2, y: 68.6 },
  { id: "cala-nera", label: "Cala Nera", x: 40.1, y: 71.1 },
  { id: "faro", label: "Faro", x: 43, y: 72.4 },
  { id: "cretazzo", label: "Cretazzo", x: 49.4, y: 79.8 },
  { id: "praia-galera", label: "Praia Galera", x: 57, y: 84.6 },
  { id: "zotta-muletti", label: "Zotta Muletti", x: 60.1, y: 85.9 },
  { id: "cala-conca", label: "Cala Conca", x: 64.3, y: 85.2 },
  { id: "curtigghiu", label: "Curtigghiu", x: 65.2, y: 89.6 },
  { id: "punta-basano", label: "Punta Basano", x: 74.6, y: 89.4 },
  { id: "finocchio-marino", label: "Finocchio Marino", x: 71.4, y: 84 },
  { id: "praia-di-mezzo", label: "Praia di Mezzo", x: 68.5, y: 82.8 },
  { id: "praia-nacchi", label: "Praia Nacchi", x: 67.6, y: 76.9 },
  { id: "madonna-del-rotolo", label: "Madonna del Rotolo", x: 64.4, y: 62.2 },
  { id: "scalo-nuovo", label: "Scalo Nuovo", x: 62.1, y: 55.8 },
  { id: "punta-san-simone", label: "Punta San Simone", x: 62.5, y: 51.9 },
  { id: "scalo-vecchio", label: "Scalo Vecchio", x: 60.7, y: 48.9 },
  { id: "bagno-femmine", label: "Bagno Femmine", x: 58.3, y: 45 },
  { id: "praia-pigna", label: "Praia Pigna", x: 56.1, y: 38.8 },
  { id: "grotta-del-cammello", label: "Grotta del Cammello", x: 54.4, y: 27.2 },
  { id: "paese", label: "Paese", x: 59.6, y: 52.5 },
];

export const islandOrder: IslandId[] = ["favignana", "levanzo", "marettimo"];

export const islandMapData: Record<IslandId, IslandMapData> = {
  favignana: {
    aspectClassName: "aspect-[1371/765]",
    height: 765,
    id: "favignana",
    imageSrc: "/images/islands/favignana/hero.webp",
    label: "Favignana",
    pois: favignanaPois,
    src: "/images/islands/favignana.svg",
    width: 1371,
    widthStyle: "min(100%, calc(112% * 1371 / 765), 64rem)",
  },
  levanzo: {
    aspectClassName: "aspect-[1185/885]",
    height: 885,
    id: "levanzo",
    imageSrc: "/images/islands/levanzo/hero.webp",
    label: "Levanzo",
    pois: levanzoPois,
    src: "/images/islands/levanzo.svg",
    width: 1185,
    widthStyle: "min(92%, calc(112% * 1185 / 885), 40rem)",
  },
  marettimo: {
    aspectClassName: "aspect-[1371/765]",
    height: 765,
    id: "marettimo",
    imageSrc: "/images/islands/marettimo/hero.webp",
    label: "Marettimo",
    pois: marettimoPois,
    src: "/images/islands/marettimo.svg",
    width: 1371,
    widthStyle: "min(100%, calc(112% * 1371 / 765), 56rem)",
  },
};
